version: "3.8"
services:
  node-app:
    build: ./
    # expose:
    #   - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    restart: unless-stopped
# version: "3"
# services:
#   server:
#     container_name: website_server
#     build: ./
#     restart: unless-stopped
#     ports:
#       - 3000:3000
#       - 5000:5000
