fragment AuthorParts on Author {
  name
  avatar
}

fragment NameParts on Name {
  navbar {
    __typename
    logo
    navitems {
      __typename
      menutitle
      menulink
    }
    navbuttons {
      __typename
      buttontitle
      buttonlink
    }
  }
  hero {
    __typename
    herotitle
    herosubtitle
    herodescription
    herobutton {
      __typename
      buttontitle
      buttonlink
    }
    heroimage
  }
  features {
    __typename
    sectiontitle
    features {
      __typename
      icon
      title
      subtitle
      description
    }
  }
  potentialuser {
    __typename
    sectiontitle
    potentialusers {
      __typename
      image
      title
      description
      button {
        __typename
        buttontext
        buttonlink
      }
    }
  }
  otherproducts {
    __typename
    productlogo {
      __typename
      productlogo
    }
  }
  footercto {
    __typename
    cto
    ctobutton {
      __typename
      buttontext
      buttonlink
    }
  }
  footer {
    __typename
    logo
    address {
      __typename
      title
      companyname
      companystreet
      companycity
      companycountry
    }
    otherdata {
      __typename
      title
      body {
        __typename
        item
        itemlink
      }
    }
  }
}

fragment SamplehomeParts on Samplehome {
  navbar {
    __typename
    logo
    navitems {
      __typename
      menutitle
      menulink
    }
    navbuttons {
      __typename
      buttontitle
      buttonlink
    }
  }
  hero {
    __typename
    herotitle
    herosubtitle
    herodescription
    herobutton {
      __typename
      buttontitle
      buttonlink
    }
    heroimage
  }
  features {
    __typename
    sectiontitle
    features {
      __typename
      icon
      title
      subtitle
      description
    }
  }
  potentialuser {
    __typename
    sectiontitle
    potentialusers {
      __typename
      users {
        __typename
        image
        title
        description
      }
    }
  }
  otherproducts {
    __typename
    productlogo {
      __typename
      productlogo
    }
  }
  footercto {
    __typename
    cto
    ctobutton {
      __typename
      buttontext
      buttonlink
    }
  }
  footer {
    __typename
    address {
      __typename
      title
      companyname
      companystreet
      companycity
      companycountry
    }
    otherdata {
      __typename
      title
      body {
        __typename
        item
        itemlink
      }
    }
  }
}
