fragment AuthorParts on Author {
  name
  avatar
}

fragment NavbarParts on Navbar {
  navbar {
    __typename
    logo {
      __typename
      link
      logo
    }
    navitems {
      __typename
      menutitle
      menulink
    }
    navbuttons {
      __typename
      buttontitle
      buttonlink
    }
  }
}

fragment FooterParts on Footer {
  logo
  address {
    __typename
    title
    companyname
    companystreet
    companycity
    companycountry
  }
  otherdata {
    __typename
    title
    body {
      __typename
      item
      itemlink
      itemtag
    }
  }
}

fragment NameParts on Name {
  hero {
    __typename
    herotitle
    sectionid
    herosubtitle
    herodescription
    herobutton {
      __typename
      buttontitle
      buttonlink
    }
    heroimage
  }
  usecases {
    __typename
    sectiontitle
    sectionid
    sideimage
    usecases {
      __typename
      title
      description
    }
  }
  banners {
    __typename
    title
    content
    bannerImage
  }
  features {
    __typename
    sectiontitle
    sectionid
    topimage
    features {
      __typename
      icon
      title
      subtitle
      description
    }
  }
  servicestest {
    __typename
    sectiontitle
    services {
      __typename
      title
      description
    }
  }
  ourapproach {
    __typename
    sectiontitle
    sectionid
    sideimage
    ourapproach {
      __typename
      title
      description
    }
  }
  potentialuser {
    __typename
    sectiontitle
    sectionid
    potentialusers {
      __typename
      image
      title
      description
      button {
        __typename
        buttontext
        buttonlink
      }
    }
  }
  otherproducts {
    __typename
    productlogo {
      __typename
      productlogo
    }
  }
  footercto {
    __typename
    cto
    sectionid
    ctobutton {
      __typename
      buttontext
      buttonlink
    }
  }
}

fragment ImpressumParts on Impressum {
  title
  description
}
