query author($relativePath: String!) {
  author(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    ...AuthorParts
  }
}

query authorConnection {
  authorConnection {
    totalCount
    edges {
      node {
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...AuthorParts
      }
    }
  }
}

query name($relativePath: String!) {
  name(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    ...NameParts
  }
}

query nameConnection {
  nameConnection {
    totalCount
    edges {
      node {
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...NameParts
      }
    }
  }
}

query samplehome($relativePath: String!) {
  samplehome(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    ...SamplehomeParts
  }
}

query samplehomeConnection {
  samplehomeConnection {
    totalCount
    edges {
      node {
        id
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...SamplehomeParts
      }
    }
  }
}
